### ISSUE TITLE
Cant see additional fields in self service.

### ISSUE THREAD

**Issue by GoempieK** [pluginsGLPI/fields#185]
I added an additional field that should be shown an all the ticket forms.
As a technician i can see the extra field, but as an self-service the field is not shown.

![image of glpi settings](http://image.prntscr.com/image/3d974fe8b1f9450ba1359a7b29938ba1.png)

**Comment by kalajar** [comment]
Hello, the same thing happened to me and these fields for the incident form are only displayed in the standard interface.

Now I have a problem because when I enter a new ticket the fields do not appear the first time, to activate I need to find a ticket that already have these fields and then if they appear, you know why this happens?

**Comment by jpclerc** [comment]
Hello
Sory for my poor english ....

The field that i have added is not present when i create the new ticket

The bloc is 'Active" as the field
the field is mandatory 
It's OK for my profil

Glpi : 9.1.2
plugin fields : 1.6.1

**Comment by kalajar** [comment]
Thank you for answering my inquiry

I commented that all the fields active, I send a screenshot with the
configuration.

I commented that the problem arises when a session ends and closes the
application and then re-enters the fields no longer appear in the main form
of the ticket

[image: Inline image 1]

[image: Inline image 2]


[image: Inline image 3]

**Comment by jpclerc** [comment]
For me, the added field never appear !

**Comment by JherekC** [comment]
We have the same issue (Glpi 9.1.6, Plugin 1.6.1).

It appears that the container won't show up because the glpi_tabs array in $_SESSION doesn't contain the 'ticket' key. This is a control done in showForTab function (field.class.php line 514).
$_SESSION['glpi_tabs']['ticket'] value is initialized when you open a existing ticket, and not at login time, nor when starting a new ticket. Unfortunately, this is the main behaviour of our self-service users - they don't check their existing tickets before creating their new issue.

We don't know if this is a plugin issue (is there another way to check the active tab ?) or a GLPI issue ($_SESSION['glpi_tabs']['ticket'] may be initialized at logon).

BTW, we have noticed that sometimes the fields are missing even for technician, as if the glpi_tabs value was reset by something, but this may happen because of a faulty plugin...

**Comment by orthagh** [comment]
1.7.0 will contains this feature request

**Comment by alfradique** [comment]
Hi!
I have the same issue.
I add field EMEI in Assets/Phones (active), but it does not appear. Using template or not.

GLPI 9.1.6.
Additional Fields 1.6.2

**Comment by Wikiki** [comment]
Hi,

We still having the issue with v1.7.0

How can we fix this ?

**Comment by sebeka** [comment]
Hi

still the same problem with glpi 9.3 and fields 1.8.1

I have to reload the computers tab after login that my custom fields are shown up.

Directly after login,  $_SESSION['glpi_tabs']  =   Array ( [central] => Central$1 )
After page reload it is: 
Array ( [central] => Central$1 [computer] => Computer$main [config] => Config$1 

Is there a solution? How can we initialize $_SESSION['glpi_tabs'] after login already?


Thanks

**Comment by sebeka** [comment]
I just want to add:
There seems to be the same issue for fusion-inventory.
In the Computer-Asset Software tab, the "fusion-inventory" Part is only shown after reload.
Maybe this is a glpi issue?

**Comment by teamghi** [comment]
i fixed it by commented this line at \plugins\fields\inc\field.class.php : 
//      if (!isset($_SESSION['glpi_tabs'][strtolower($item::getType())])) {
//         return;
//      };
but i don't know whether it impact to other function ?

**Comment by audetpascale** [comment]
I had the issue also, on my side, the fix was almost like @teamghi , but I have done:
```php
      if (!isset($_SESSION['glpi_tabs'][strtolower($item::getType())])) {
          $_SESSION['glpi_tabs'][strtolower($item::getType())] = -1;
      };
```

I don't think there is any side effects... but if you got info, thanks for letting me know!

**Comment by guillermohaad** [comment]
hi @audetpascale 
I made the change but I still don't see the fields in the sef-sercices profile? should i do something else?
I have glpi 9.1.6 and fields 1.6.2 installed

**Comment by guillermohaad** [comment]
This solution gives @audetpascale , it worked for me with the version Additionnal fields 1.8.2 and glpi 9.3.1
Thank you

**Comment by audetpascale** [comment]
Hi @guillermohaad , we are working on 9.1.2 and the plugin is 1.5.0 , kindda strange since we have an older version ;)
