### ISSUE TITLE
Additional Fields Loading Issue.

### ISSUE THREAD

**Issue by sbind29893** [pluginsGLPI/fields#240]
I have used fields plugin to create fields in my computer add form, issue is sometimes fields which i have made using addition fields plugin doesn't get loaded. i have to refresh and then it gets loaded.

**Comment by stdonato** [comment]
I have the same problem.

**Comment by juveboss** [comment]
Me too...

**Comment by cedric-anne** [comment]
Hi, @sbind29893 @stdonato @juveboss 

Which version of plugin and GLPI are you using ?
Can you check if you have javascript error in your console ?

Thanks

**Comment by juveboss** [comment]
Hello, i use 1.7.2 plugin and 9.2.2 for GLPI.

Here the source code when is the functional and the other when the plugin don't work.

[plugin-work.txt](https://github.com/pluginsGLPI/fields/files/2048766/plugin-work.txt)

[plugin-not-work.txt](https://github.com/pluginsGLPI/fields/files/2048767/plugin-not-work.txt)

**Comment by trasher** [comment]
Source code a a page is probably not relevant. Please explain your issue, and provide any logs, etc.

**Comment by juveboss** [comment]
I don't know how to do...

Can you provide the files ? @sbind29893 @stdonato 

Thanks

**Comment by xerodan** [comment]
I have had this problem for some time. The log files have no entry and if you activate the debug mode no error message appears.
The occasion that the additional fields in the ticket are not displayed happens randomly and after a page refresh everything is ok again in 95% of the cases.
It appeared in GLPI version 9.1.x and currently in version 9.2.1.
Plugin version of Fields is 1.7. I just saw that there is a newer version of the plugin I haven't tested it with yet.

**Comment by ladenree76000** [comment]
glpi 9.3.1 + fields 1.8.2 :
 when using glpi split view : can not  see fields Added to ticket body,  KO
  switch to classical view or left TAB can see  field Added to ticket body, OK
switch back to split view  then I can see fiels Added to ticket body  OK  
until I log off/ log in :  KO again
(

**Comment by iggytof** [comment]
After many tests, the issue described above by ladenree76000 appeared with the version 1.5.0 because in version 1.4.5, the fields appear well in the split view 

GLPI 9.1.7.1 + FIELDS 1.4.5 -> OK
GLPI 9.1.7.1 + FIELDS 1.5.0+ ->KO

**Comment by juveboss** [comment]
Hello,

the problem is fixed on version 1.9? Because it's a problem that have been coming from several versions..

Glpi : 9.3.1   Fields : 1.8.2 => KO

Thanks in advance

**Comment by kedson42** [comment]
Hello.
I still face the same problem: additional fields sometimes are displayed and sometimes don't. When they don't, a page refresh is necessary.
Has anyone worked in a solution yet?

**Comment by juveboss** [comment]
Hello,

Up 

soon in a release?

**Comment by stonebuzz** [comment]
duplicate with #328

**Comment by stonebuzz** [comment]
Fixed by #352
